In [1]:
import numpy as np

In [7]:
a = np.array([1,2,3,4,5], dtype="i")
b = np.array((0,6,7,8,9))
c = np.array((0,6,7,8,9), dtype='f')

In [4]:
type(a)

numpy.ndarray

In [5]:
type(b)

numpy.ndarray

In [8]:
type(c)

numpy.ndarray

In [13]:
a.dtype

dtype('int32')

In [14]:
b.dtype

dtype('int64')

In [15]:
c.dtype

dtype('float32')

In [31]:
d=np.array([[1,2,3],[4,5,6]])
e=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [21]:
type(d)

numpy.ndarray

In [22]:
d.dtype

dtype('int64')

In [23]:
d.ndim

2

In [24]:
d.shape

(2, 3)

In [32]:
e.ndim

3

In [33]:
e.shape

(2, 2, 2)

In [37]:
a = np.arange(100)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [39]:
b = np.arange(20,100)
print(b)

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67
 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91
 92 93 94 95 96 97 98 99]


In [41]:
c = np.arange(20,100,5)
print(c)

[20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [44]:
a = np.random.permutation(a)
print(a)

[56 20 14 11  0 48 58 17 19 70  3 45 13 16  9  2 79 47 28 72 44 21  6 67
 82 93 43 76 26 69 96 73 10 12 30 71 53 87 66 81 75 80 38 49  7 37 39 84
 90 60 77 40 36 89 34 99 18 83 57 54 15 59 42 98 29 65 41 86 74 62 51  1
 64 92 85 35  4 25 27 94 24  5 61 78 22 55 33 46 23 50  8 68 32 31 97 52
 88 63 91 95]


In [45]:
np.random.randint(20,50)

46

In [47]:
b = np.random.rand(2,3,4)
print(b)

[[[0.89754861 0.87690905 0.92126084 0.83858868]
  [0.47587696 0.10318091 0.16874758 0.43555105]
  [0.80652639 0.79721095 0.2451264  0.07812557]]

 [[0.85197649 0.48248241 0.33015348 0.24904732]
  [0.72398403 0.53905325 0.35349249 0.34072227]
  [0.4396089  0.26684147 0.1286724  0.1635444 ]]]


In [48]:
np.arange(24).reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])