In [1]:
import numpy as np

In [7]:
a = np.array([1,2,3,4,5], dtype="i")
b = np.array((0,6,7,8,9))
c = np.array((0,6,7,8,9), dtype='f')

In [4]:
type(a)

numpy.ndarray

In [5]:
type(b)

numpy.ndarray

In [8]:
type(c)

numpy.ndarray

In [13]:
a.dtype

dtype('int32')

In [14]:
b.dtype

dtype('int64')

In [15]:
c.dtype

dtype('float32')

In [31]:
d=np.array([[1,2,3],[4,5,6]])
e=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [21]:
type(d)

numpy.ndarray

In [22]:
d.dtype

dtype('int64')

In [23]:
d.ndim

2

In [24]:
d.shape

(2, 3)

In [32]:
e.ndim

3

In [33]:
e.shape

(2, 2, 2)

In [37]:
a = np.arange(100)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [39]:
b = np.arange(20,100)
print(b)

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67
 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91
 92 93 94 95 96 97 98 99]


In [41]:
c = np.arange(20,100,5)
print(c)

[20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [44]:
a = np.random.permutation(a)
print(a)

[56 20 14 11  0 48 58 17 19 70  3 45 13 16  9  2 79 47 28 72 44 21  6 67
 82 93 43 76 26 69 96 73 10 12 30 71 53 87 66 81 75 80 38 49  7 37 39 84
 90 60 77 40 36 89 34 99 18 83 57 54 15 59 42 98 29 65 41 86 74 62 51  1
 64 92 85 35  4 25 27 94 24  5 61 78 22 55 33 46 23 50  8 68 32 31 97 52
 88 63 91 95]


In [45]:
np.random.randint(20,50)

46

In [47]:
b = np.random.rand(2,3,4)
print(b)

[[[0.89754861 0.87690905 0.92126084 0.83858868]
  [0.47587696 0.10318091 0.16874758 0.43555105]
  [0.80652639 0.79721095 0.2451264  0.07812557]]

 [[0.85197649 0.48248241 0.33015348 0.24904732]
  [0.72398403 0.53905325 0.35349249 0.34072227]
  [0.4396089  0.26684147 0.1286724  0.1635444 ]]]


In [48]:
np.arange(24).reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [51]:
np.arange(100).reshape(4,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [53]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [55]:
b = a[2:8].copy()
# hard copy of a, if without copy(), it copied only the reference
print(b)

[2 3 4 5 6 7]


In [58]:
print(b[::-1]) # reverse the list
print(b[::-2])

[7 6 5 4 3 2]
[7 5 3]


In [63]:
a = np.array([0,1,2,3,4,5,6,7,7,8,9,0])
idx1 = np.argwhere(a==0)
print(idx1)

[[ 0]
 [11]]


In [64]:
idx2 = np.argwhere(a==7)
print(idx2)

[[7]
 [8]]


In [73]:
a = np.arange(30).reshape(5,6)
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [74]:
a[1,3]

9

In [75]:
a[1,:]

array([ 6,  7,  8,  9, 10, 11])

In [76]:
a[:,1]

array([ 1,  7, 13, 19, 25])

In [77]:
a[1:3,2:4]

array([[ 8,  9],
       [14, 15]])

In [78]:
a.T

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

In [79]:
b = np.random.permutation(np.arange(30)).reshape(5,6)
print(b)

[[16  9 24 27 26  6]
 [18  7  0 10  2  1]
 [28  8 20 19 15 22]
 [12 25  3 23  5 11]
 [ 4 13 21 29 17 14]]


In [81]:
b.sort(axis=0)
print(b)

[[ 4  7  0 10  2  1]
 [12  8  3 19  5  6]
 [16  9 20 23 15 11]
 [18 13 21 27 17 14]
 [28 25 24 29 26 22]]


In [82]:
b.sort(axis=1)
print(b)

[[ 0  1  2  4  7 10]
 [ 3  5  6  8 12 19]
 [ 9 11 15 16 20 23]
 [13 14 17 18 21 27]
 [22 24 25 26 28 29]]


In [83]:
b[b<8]

array([0, 1, 2, 4, 7, 3, 5, 6])

In [85]:
b[[1,3,4]]

array([[ 3,  5,  6,  8, 12, 19],
       [13, 14, 17, 18, 21, 27],
       [22, 24, 25, 26, 28, 29]])

In [87]:
b[(b>5) & (b<20)]

array([ 7, 10,  6,  8, 12, 19,  9, 11, 15, 16, 13, 14, 17, 18])

In [91]:
a = np.round(10*np.random.rand(2,3)).astype(int)
print(a)

[[4 8 6]
 [9 3 3]]


In [96]:
# broadcasting
b = a + 1
print(b)

[[ 5  9  7]
 [10  4  4]]


In [95]:
b = a + np.array([[3],[2]])
print(b)

[[ 7 11  9]
 [11  5  5]]
