In [1]:
import numpy as np

In [4]:
a = np.array([1,2,3,4,5], dtype="i")
b = np.array((0,6,7,8,9))
c = np.array((0,6,7,8,9), dtype='f')

In [5]:
type(a)

numpy.ndarray

In [6]:
type(b)

numpy.ndarray

In [7]:
type(c)

numpy.ndarray

In [8]:
a.dtype

dtype('int32')

In [9]:
b.dtype

dtype('int64')

In [10]:
c.dtype

dtype('float32')

In [11]:
d=np.array([[1,2,3],[4,5,6]])
e=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [12]:
type(d)

numpy.ndarray

In [13]:
d.dtype

dtype('int64')

In [14]:
d.ndim

2

In [15]:
d.shape

(2, 3)

In [16]:
e.ndim

3

In [17]:
e.shape

(2, 2, 2)

In [18]:
a = np.arange(100)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [19]:
b = np.arange(20,100)
print(b)

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67
 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91
 92 93 94 95 96 97 98 99]


In [20]:
c = np.arange(20,100,5)
print(c)

[20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [21]:
a = np.random.permutation(a)
print(a)

[96 52 36 66 60 15 86 47 31 71 76 28 32 55 48 70 81 98 84 73 11 69 97 78
 37 14 21 23 22  9 41 74 20  8 17 10 40 93 61 42 91 27 29 92 33 99 80 79
 63 85 13  3  4 30 67  0 46  7 87 34 89 90 75 88  2 72 24 77 95 18 12 53
  5 59 44 25 54 58 51 43 49 38 26 45 82 57 19 68 64 56 94 62 83 65 50 39
 16  6  1 35]


In [22]:
np.random.randint(20,50)

38

In [23]:
b = np.random.rand(2,3,4)
print(b)

[[[0.22945599 0.08174855 0.69659239 0.42303941]
  [0.19645311 0.47721664 0.77933415 0.79609629]
  [0.40310325 0.46486614 0.81894805 0.45913253]]

 [[0.42950519 0.34795306 0.30696622 0.19332097]
  [0.45339839 0.62499999 0.73190143 0.49726988]
  [0.67754937 0.89966389 0.87916555 0.96650803]]]


In [24]:
np.arange(24).reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [25]:
np.arange(100).reshape(4,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [26]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [27]:
b = a[2:8].copy()
# hard copy of a, if without copy(), it copied only the reference
print(b)

[2 3 4 5 6 7]


In [28]:
print(b[::-1]) # reverse the list
print(b[::-2])

[7 6 5 4 3 2]
[7 5 3]


In [29]:
a = np.array([0,1,2,3,4,5,6,7,7,8,9,0])
idx1 = np.argwhere(a==0)
print(idx1)

[[ 0]
 [11]]


In [30]:
idx2 = np.argwhere(a==7)
print(idx2)

[[7]
 [8]]


In [31]:
a = np.arange(30).reshape(5,6)
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [32]:
a[1,3]

9

In [33]:
a[1,:]

array([ 6,  7,  8,  9, 10, 11])

In [34]:
a[:,1]

array([ 1,  7, 13, 19, 25])

In [35]:
a[1:3,2:4]

array([[ 8,  9],
       [14, 15]])

In [36]:
a.T

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

In [37]:
b = np.random.permutation(np.arange(30)).reshape(5,6)
print(b)

[[ 0 20 17  1  3 25]
 [28  9 12  6  4 19]
 [ 2  8 26 15  5 21]
 [24 29 23 22  7 16]
 [13 27 14 18 10 11]]


In [38]:
b.sort(axis=0)
# Sort by column
print(b)

[[ 0  8 12  1  3 11]
 [ 2  9 14  6  4 16]
 [13 20 17 15  5 19]
 [24 27 23 18  7 21]
 [28 29 26 22 10 25]]


In [39]:
b.sort(axis=1)
# sort by row
print(b)

[[ 0  1  3  8 11 12]
 [ 2  4  6  9 14 16]
 [ 5 13 15 17 19 20]
 [ 7 18 21 23 24 27]
 [10 22 25 26 28 29]]


In [40]:
b[b<8]

array([0, 1, 3, 2, 4, 6, 5, 7])

In [41]:
b[[1,3,4]]

array([[ 2,  4,  6,  9, 14, 16],
       [ 7, 18, 21, 23, 24, 27],
       [10, 22, 25, 26, 28, 29]])

In [42]:
b[(b>5) & (b<20)]

array([ 8, 11, 12,  6,  9, 14, 16, 13, 15, 17, 19,  7, 18, 10])

In [43]:
a = np.round(10*np.random.rand(2,3)).astype(int)
print(a)

[[0 9 1]
 [2 7 7]]


In [44]:
# broadcasting
b = a + 1
print(b) 

[[ 1 10  2]
 [ 3  8  8]]


In [45]:
b = a + np.array([[3],[2]])
print(b)

[[ 3 12  4]
 [ 4  9  9]]


In [54]:
b = b.reshape(6)

In [55]:
b == 9

array([False, False, False, False,  True,  True])

In [58]:
np.arange(b.size)

array([0, 1, 2, 3, 4, 5])

In [62]:
indexOfNine = (b==9)*np.arange(b.size)
print(indexOfNine)

[0 0 0 0 4 5]


In [60]:
indexOfNine = np.argwhere(b==9)
print(indexOfNine)

[[4]
 [5]]


In [64]:
b

array([ 3, 12,  4,  4,  9,  9])

In [71]:
b=b.reshape(2,3)

In [72]:
a = np.arange(4).reshape(2,2)
print(a)

[[0 1]
 [2 3]]


In [73]:
np.hstack((a,b))

array([[ 0,  1,  3, 12,  4],
       [ 2,  3,  4,  9,  9]])

In [87]:
c = np.arange(8).reshape(4,2)
print(c)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [88]:
np.vstack((a,c))

array([[0, 1],
       [2, 3],
       [0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [81]:
strings = np.array(["dzy", "def", "abc", "abcde"])
strings.sort()
print(strings)

['abc' 'abcde' 'def' 'dzy']


In [2]:
np.array([0.00001234, 123456.789])

array([1.23400000e-05, 1.23456789e+05])

In [3]:
np.set_printoptions(suppress=True)
print(np.array([0.00001234, 123456.789]))  # Output: [     0.00001234 123456.789     ]

[     0.00001234 123456.789     ]
