In [1]:
import numpy as np

In [6]:
# numpy array of size 10, filled with zeros
a = np.array([0] * 10)
print(a)

[0 0 0 0 0 0 0 0 0 0]


In [10]:
# numpy array with 10 - 49
b = np.arange(10, 50)
print(b)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [21]:
# numpy array matrix 2*2, filled with ones
c = np.array([[1, 1]] * 2)
print(c)
c.dtype

[[1 1]
 [1 1]]


dtype('int64')

In [25]:
# numpy array matrix 3 * 2, fill with tens, datatype float
d = np.full((3,2), 10, dtype=np.float16)
print(d)

[[10. 10.]
 [10. 10.]
 [10. 10.]]


In [31]:
# create numpy array same shape and type as X, filled with twos
X = np.arange(4, dtype=np.int16)
print(X)
X_like = np.full_like(X, 2)
print(X_like)

[0 1 2 3]
[2 2 2 2]


In [32]:
# create new numpy matri with same shape and type as X, filled with zeros
Y = np.array([[1,2,3], [4,5,6]], dtype=np.float16)
print(Y)
Y_like = np.full_like(Y, 0)
print(Y_like)

[[1. 2. 3.]
 [4. 5. 6.]]
[[0. 0. 0.]
 [0. 0. 0.]]
