In [1]:
import numpy as np

In [2]:
# numpy array of size 10, filled with zeros
a = np.array([0] * 10)
print(a)

[0 0 0 0 0 0 0 0 0 0]


In [3]:
# numpy array with 10 - 49
b = np.arange(10, 50)
print(b)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [4]:
# numpy array matrix 2*2, filled with ones
c = np.array([[1, 1]] * 2)
print(c)
c.dtype

[[1 1]
 [1 1]]


dtype('int64')

In [5]:
# numpy array matrix 3 * 2, fill with tens, datatype float
d = np.full((3,2), 10, dtype=np.float16)
print(d)

[[10. 10.]
 [10. 10.]
 [10. 10.]]


In [6]:
# create numpy array same shape and type as X, filled with twos
X = np.arange(4, dtype=np.int16)
print(X)
X_like = np.full_like(X, 2)
print(X_like)

[0 1 2 3]
[2 2 2 2]


In [7]:
# create new numpy matri with same shape and type as X, filled with zeros
Y = np.array([[1,2,3], [4,5,6]], dtype=np.float16)
print(Y)
Y_like = np.full_like(Y, 0)
print(Y_like)

[[1. 2. 3.]
 [4. 5. 6.]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [9]:
# create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
# create a numpy array, filled with 5 random integer values between 1 and 10
np.random.randint(1, 11, size=5)

array([10,  7, 10,  5,  4])

In [21]:
# create a 3*3*3 numpy matrix, filled with random float values
np.random.randn(3,3,3)

array([[[ 0.15822268, -0.71457814,  1.90133843],
        [-0.19881619, -0.28414822,  0.8867717 ],
        [-1.14226394, -0.48008259, -0.98900108]],

       [[ 0.87708775, -2.56545149,  1.83126609],
        [-0.59798368, -1.59158256,  1.28689289],
        [ 0.63755397, -1.09696217,  0.59636814]],

       [[-1.0268558 ,  1.83252449, -0.20140749],
        [-0.6505625 ,  0.75952005,  0.36846364],
        [ 2.39722085,  0.00289618, -2.08704731]]])