In [14]:
import numpy as np

# Example data
output = np.array([1, 2, 3, 4])  # 1D output array with 4 samples
# features = np.array([[1, 5],     # Feature matrix with 4 samples and 2 features
#                      [2, 4],
#                      [3, 3],
#                      [4, 2]])

features = np.array([[1, 5, 4],     # Feature matrix with 4 samples and 2 features
                     [2, 4, 4],
                     [3, 3, 3],
                     [4, 2, 3]])

# Concatenate the output as a new column in the features matrix

# Compute the correlation matrix
correlation_matrix = np.corrcoef(features, output, rowvar=False)

# Extract the correlations between output (first row/col) and the features
correlations_with_output = correlation_matrix
print(correlations_with_output)


[[ 1.         -1.         -0.89442719  1.        ]
 [-1.          1.          0.89442719 -1.        ]
 [-0.89442719  0.89442719  1.         -0.89442719]
 [ 1.         -1.         -0.89442719  1.        ]]


In [15]:

correlations_with_output = correlation_matrix[0, 1:]  # The first row (output) with all other features

print(correlations_with_output)


[-1.         -0.89442719  1.        ]


In [16]:
output[2]


3

In [17]:
output[0,0]


IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [18]:
zero, one, two, three = output
print(zero, one, two, three)


1 2 3 4


In [19]:
output1 = np.array([2, 2, 2, 2])

output1 == output1[0]


array([ True,  True,  True,  True])

In [20]:
np.all(output1 == output1[0])


True

In [21]:
np.all(output == output[0])


False

In [22]:
output == output[0]


array([ True, False, False, False])

In [25]:
bags = np.random.randint(features.shape[0], size=(3, features.shape[0]))
for bag in bags:
    print(bag, features[bag])
    print("===============")


[3 1 3 1] [[4 2 3]
 [2 4 4]
 [4 2 3]
 [2 4 4]]
[3 2 3 3] [[4 2 3]
 [3 3 3]
 [4 2 3]
 [4 2 3]]
[1 1 2 3] [[2 4 4]
 [2 4 4]
 [3 3 3]
 [4 2 3]]


In [32]:
rng = np.random.default_rng()
feature_bagged = rng.choice(features, features.shape[0], axis=0)
feature_bagged


array([[1, 5, 4],
       [2, 4, 4],
       [1, 5, 4],
       [4, 2, 3]])

In [40]:
samples = rng.choice(features.shape[0], features.shape[0], axis=0)
samples


array([2, 1, 1, 3])

In [41]:
features_bagged = features[samples]
features_bagged


array([[3, 3, 3],
       [2, 4, 4],
       [2, 4, 4],
       [4, 2, 3]])

In [42]:
output_bagged = output[samples]
output_bagged


array([3, 2, 2, 4])

In [56]:
import pandas as pd

df = pd.DataFrame({"Col1": [0, 20, 0, 0, -20],
                   "Col2": [-7, 0, 0, 3, 0],
                   "Col3": [7, -20, 0, -3, 20]},
                  index=pd.date_range("2020-01-01", "2020-01-05"))

df2 = pd.DataFrame(0,index=df.index, columns=df.columns)
df2


,Col1,Col2,Col3
2020-01-01,0,0,0
2020-01-02,0,0,0
2020-01-03,0,0,0
2020-01-04,0,0,0
2020-01-05,0,0,0


In [57]:
df2.at["2020-01-01", "Col3"] = 100
df2


,Col1,Col2,Col3
2020-01-01,0,0,100
2020-01-02,0,0,0
2020-01-03,0,0,0
2020-01-04,0,0,0
2020-01-05,0,0,0


In [58]:
df2 = df + df2.shift(1, fill_value=0)
df2


,Col1,Col2,Col3
2020-01-01,0,-7,7
2020-01-02,20,0,80
2020-01-03,0,0,0
2020-01-04,0,3,-3
2020-01-05,-20,0,20


In [59]:
df.iloc[1:]


,Col1,Col2,Col3
2020-01-02,20,0,-20
2020-01-03,0,0,0
2020-01-04,0,3,-3
2020-01-05,-20,0,20


In [60]:
df3 = pd.DataFrame(0,index=df.index, columns=df.columns)
df3.at["2020-01-01", "Col3"] = 100
df3


,Col1,Col2,Col3
2020-01-01,0,0,100
2020-01-02,0,0,0
2020-01-03,0,0,0
2020-01-04,0,0,0
2020-01-05,0,0,0


In [61]:
df3.iloc[0] = df.iloc[0] + df3.iloc[0]
df3


,Col1,Col2,Col3
2020-01-01,0,-7,107
2020-01-02,0,0,0
2020-01-03,0,0,0
2020-01-04,0,0,0
2020-01-05,0,0,0


In [62]:
df3.shift(1).iloc[1:]


,Col1,Col2,Col3
2020-01-02,0.0,-7.0,107.0
2020-01-03,0.0,0.0,0.0
2020-01-04,0.0,0.0,0.0
2020-01-05,0.0,0.0,0.0


In [63]:
df3.shift(1).iloc[1:]
df3


,Col1,Col2,Col3
2020-01-01,0,-7,107
2020-01-02,0,0,0
2020-01-03,0,0,0
2020-01-04,0,0,0
2020-01-05,0,0,0


In [64]:
df3.iloc[1:] = df.iloc[1:] + df3.shift(1).iloc[1:]
df3


,Col1,Col2,Col3
2020-01-01,0,-7,107
2020-01-02,20,-7,87
2020-01-03,0,0,0
2020-01-04,0,3,-3
2020-01-05,-20,0,20


In [68]:
dfcumsum = df.cumsum()
dfcumsum


,Col1,Col2,Col3
2020-01-01,0,-7,7
2020-01-02,20,-7,-13
2020-01-03,20,-7,-13
2020-01-04,20,-4,-16
2020-01-05,0,-4,4


In [69]:
dfcumsum["Col3"] += 100
dfcumsum


,Col1,Col2,Col3
2020-01-01,0,-7,107
2020-01-02,20,-7,87
2020-01-03,20,-7,87
2020-01-04,20,-4,84
2020-01-05,0,-4,104


In [66]:
import pandas as pd

# Create the original DataFrame
df = pd.DataFrame({
    "Col1": [0, 20, 0, 0, -20],
    "Col2": [-7, 0, 0, 3, 0],
    "Col3": [7, -20, 0, -3, 20]
}, index=pd.date_range("2020-01-01", "2020-01-05"))

# Create df3 and set the initial value
df3 = pd.DataFrame(0, index=df.index, columns=df.columns)
df3.at["2020-01-01", "Col3"] = 100
df3.iloc[0] = df.iloc[0] + df3.iloc[0]
# Calculate the values for df3 row by row
for i in range(1, len(df3)):
    df3.iloc[i] = df.iloc[i] + df3.iloc[i-1]

print(df3)


            Col1  Col2  Col3
2020-01-01     0    -7   107
2020-01-02    20    -7    87
2020-01-03    20    -7    87
2020-01-04    20    -4    84
2020-01-05     0    -4   104


In [70]:
df = pd.DataFrame({
    'col1': [1, 2, 3]
})
df = df * 2
df


,col1
0,2
1,4
2,6


In [3]:
import pandas as pd
df = pd.DataFrame({
    'col1': [1, 2, 3, 1, 5]
})
df.shift(1)


,col1
0,NaN
1,1.0
2,2.0
3,3.0
4,1.0


In [4]:
df_diff = df - df.shift(1)
df_diff


,col1
0,NaN
1,1.0
2,1.0
3,-2.0
4,4.0


In [15]:
for index, row in df_diff.iterrows():
    print("index = ", index, "; row = ", row.iloc[0])


index =  0 ; row =  nan
index =  1 ; row =  1.0
index =  2 ; row =  1.0
index =  3 ; row =  -2.0
index =  4 ; row =  4.0


In [5]:
import pandas as pd

# Sample data
data = {
    'Date': pd.date_range(start='2023-01-01', periods=7, freq='D'),
    'Price': [100, 102, 101, 105, 107, 110, 112]
}

# Create DataFrame
df = pd.DataFrame(data, )
df.set_index('Date', inplace=True)
df


,Price
Date,
2023-01-01,100
2023-01-02,102
2023-01-03,101
2023-01-04,105
2023-01-05,107
2023-01-06,110
2023-01-07,112


In [ ]:
n_day_return = (df / df.shift(3)) - 1
n_day_return


,Price
Date,
2023-01-01,NaN
2023-01-02,NaN
2023-01-03,NaN
2023-01-04,0.050000
2023-01-05,0.049020
2023-01-06,0.089109
2023-01-07,0.066667


In [ ]:
df2 = (df.shift(-3)/df) - 1
df2


,Price
Date,
2023-01-01,0.050000
2023-01-02,0.049020
2023-01-03,0.089109
2023-01-04,0.066667
2023-01-05,NaN
2023-01-06,NaN
2023-01-07,NaN


In [ ]:
df3 = df.shift(1)
df3


,Price
Date,
2023-01-01,NaN
2023-01-02,100.0
2023-01-03,102.0
2023-01-04,101.0
2023-01-05,105.0
2023-01-06,107.0
2023-01-07,110.0


In [1]:
import numpy as np

# Create an array with random values of -1, 0, or 1
array = np.random.choice([-1, 0, 1], size=(10, 10))

print(array)


[[ 0  0  0  1 -1  1  1 -1 -1  1]
 [ 0  1 -1 -1 -1  1  1  1  1  0]
 [-1  1  1 -1  0 -1  0  1  0 -1]
 [ 1  0 -1 -1  1  1 -1  1  1  0]
 [ 0 -1 -1  1 -1  0  0  1  1  0]
 [-1  1  1  1  0  1 -1 -1  0  1]
 [ 0  0  0  0  1 -1 -1 -1 -1  1]
 [ 0 -1  0  1  1  1 -1 -1 -1 -1]
 [ 1  1  1  0  0 -1  1  1 -1  1]
 [-1  1  1  0  1 -1 -1  0 -1 -1]]


In [ ]:
from scipy.stats import mode
mode_results = mode(array, axis=0)
print(mode_results[0])
print(mode_results[1])


[ 0  1  1  1  1  1 -1  1 -1  1]
[5 5 4 4 4 5 5 5 5 4]


In [ ]:
signals, counts = np.unique(array, axis=0, return_counts=True)
